Towzin Source/Towzin/Models/ProductionLineTechnicalProblem.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Towzin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionLineTechnicalProblem
    {
        public long ID { get; set; }
        public long ProductionLineID { get; set; }
        public long TechnicalProblemID { get; set; }
        public long PartID { get; set; }
        public string DescriptionTechnicalProblem { get; set; }
        public string SolutionTechnicalProblem { get; set; }
        public string Description { get; set; }
        public bool State { get; set; }
        public string Creator { get; set; }
        public System.DateTime AddDate { get; set; }
        public string LastModifier { get; set; }
        public System.DateTime LastModificationDate { get; set; }
        public byte[] Version { get; set; }
        public long OperatorID { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual ProductionLine ProductionLine { get; set; }
        public virtual TechnicalProblem TechnicalProblem { get; set; }
        public virtual Operator Operator { get; set; }
    }
}

Towzin Source/Towzin/Controllers/ProductionLineTechnicalProblemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Towzin.Models;
using PagedList;
using Microsoft.AspNet.Identity;

namespace Towzin.Controllers
{
    public class ProductionLineTechnicalProblemsController : Controller
    {
        private TowzinEntities1 db = new TowzinEntities1();

        // GET: ProductionLineTechnicalProblems
        
        [Authorize(Roles = "ProductionLineTechnicalProblem_Index , admin")]
        public async Task<ActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.T1SortParm = String.IsNullOrEmpty(sortOrder) ? "T1" : "";
            ViewBag.T2SortParm = sortOrder == "T2" ? "T2_desc" : "T2";
            ViewBag.T3SortParm = sortOrder == "T3" ? "T3_desc" : "T3";
            ViewBag.T4SortParm = sortOrder == "T4" ? "T4_desc" : "T4";
            ViewBag.T5SortParm = sortOrder == "T5" ? "T5_desc" : "T5";
            ViewBag.T6SortParm = sortOrder == "T6" ? "T6_desc" : "T6";
            ViewBag.T7SortParm = sortOrder == "T7" ? "T7_desc" : "T7";
            ViewBag.T8SortParm = sortOrder == "T8" ? "T8_desc" : "T8";
            ViewBag.T9SortParm = sortOrder == "T9" ? "T9_desc" : "T9";



            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var VW_ProductionLineTechnicalProblem_Index = from s in db.VW_ProductionLineTechnicalProblem_Index
                                select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                VW_ProductionLineTechnicalProblem_Index = VW_ProductionLineTechnicalProblem_Index.Where(s => s.ProductionLineName.Contains(searchString) || s.TechnicalProblemsName.Contains(searchString) || s.Name.ToString().Contains(searchString) || s.PartCode.ToString().Contains(searchString) || s.OperatorName.ToString().Contains(searchString) || s.DescriptionTechnicalProblem.ToString().Contains(searchString) || s.SolutionTechnicalProblem.ToString().Contains(searchString) || s.Description.ToString().Contains(searchString) || s.State.ToString().Contains(searchString));
            }
            switch (sortOrder)
            {
                case "T1_desc":
                    VW_ProductionLineTechnicalProblem_Index = VW_ProductionLineTechnicalProblem_Index.OrderByDescending(s => s.ProductionLineName);
                    break;
                case "T2_desc":
                    VW_ProductionLineTechnicalProblem_Index = VW_ProductionLineTechnicalProblem_Index.OrderByDescending(s => s.TechnicalProblemsName);
                    break;
                case "T2":
                    VW_ProductionLineTechnicalProblem_Index = VW_ProductionLineTechnicalProblem_Index.OrderBy(s => s.TechnicalProblemsName);
                    break;
                case "T3_desc":
                    VW_ProductionLineTechnicalProblem_Index = VW_ProductionLineTechnicalProblem_Index.OrderByDescending(s => s.Name);
                    break;
                case "T3":
                    VW_ProductionLineTechnicalProblem_Index = VW_ProductionLineTechnicalProblem_Index.OrderBy(s => s.Name);
                    break;
                case "T4_desc":
                    VW_ProductionLineTechnicalProblem_Index = VW_ProductionLineTechnicalProblem_Index.OrderByDescending(s => s.PartCode);
                    break;
                case "T4":
                    VW_ProductionLineTechnicalProblem_Index = VW_ProductionLineTechnicalProblem_Index.OrderBy(s => s.PartCode);
                    break;
                case "T5_desc":
                    VW_ProductionLineTechnicalProblem_Index = VW_ProductionLineTechnicalProblem_Index.OrderByDescending(s => s.OperatorName);
                    break;
                case "T5":
                    VW_ProductionLineTechnicalProblem_Index = VW_ProductionLineTechnicalProblem_Index.OrderBy(s => s.OperatorName);
                    break;
                case "T6_desc":
                    VW_ProductionLineTechnicalProblem_Index = VW_ProductionLineTechnicalProblem_Index.OrderByDescending(s => s.DescriptionTechnicalProblem);
                    break;
                case "T6":
                    VW_ProductionLineTechnicalProblem_Index = VW_ProductionLineTechnicalProblem_Index.OrderBy(s => s.DescriptionTechnicalProblem);
                    break;
                case "T7_desc":
                    VW_ProductionLineTechnicalProblem_Index = VW_ProductionLineTechnicalProblem_Index.OrderByDescending(s => s.SolutionTechnicalProblem);
                    break;
                case "T7":
                    VW_ProductionLineTechnicalProblem_Index = VW_ProductionLineTechnicalProblem_Index.OrderBy(s => s.SolutionTechnicalProblem);
                    break;
                case "T8_desc":
                    VW_ProductionLineTechnicalProblem_Index = VW_ProductionLineTechnicalProblem_Index.OrderByDescending(s => s.DescriptionTechnicalProblem);
                    break;
                case "T8":
                    VW_ProductionLineTechnicalProblem_Index = VW_ProductionLineTechnicalProblem_Index.OrderBy(s => s.DescriptionTechnicalProblem);
                    break;
                case "T9_desc":
                    VW_ProductionLineTechnicalProblem_Index = VW_ProductionLineTechnicalProblem_Index.OrderByDescending(s => s.State);
                    break;
                case "T9":
                    VW_ProductionLineTechnicalProblem_Index = VW_ProductionLineTechnicalProblem_Index.OrderBy(s => s.State);
                    break;

                default:
                    VW_ProductionLineTechnicalProblem_Index = VW_ProductionLineTechnicalProblem_Index.OrderBy(s => s.ProductionLineName);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(VW_ProductionLineTechnicalProblem_Index.ToPagedList(pageNumber, pageSize));
        }

        // GET: ProductionLineTechnicalProblems/Details/5
        
        [Authorize(Roles = "ProductionLineTechnicalProblem_Detail , admin")]
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductionLineTechnicalProblem productionLineTechnicalProblem = await db.ProductionLineTechnicalProblem.FindAsync(id);
            if (productionLineTechnicalProblem == null)
            {
                return HttpNotFound();
            }
            return View(productionLineTechnicalProblem);
        }

        // GET: ProductionLineTechnicalProblems/Create
        
        [Authorize(Roles = "ProductionLineTechnicalProblem_Create , admin")]
        public ActionResult Create()
        {
            ViewBag.PartID = new SelectList(db.Part, "ID", "Name");
            ViewBag.ProductionLineID = new SelectList(db.ProductionLine, "ID", "ProductionLineName");
            ViewBag.TechnicalProblemID = new SelectList(db.TechnicalProblem, "ID", "TechnicalProblemsName");
            ViewBag.OperatorID = new SelectList(db.Operator, "OperatorID", "OperatorName");
            return View();
        }

        // POST: ProductionLineTechnicalProblems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        [Authorize(Roles = "ProductionLineTechnicalProblem_Create , admin")]
        public async Task<ActionResult> Create([Bind(Include = "ID,ProductionLineID,TechnicalProblemID,PartID,DescriptionTechnicalProblem,SolutionTechnicalProblem,Description,State,Creator,AddDate,LastModifier,LastModificationDate,Version,OperatorID")] ProductionLineTechnicalProblem productionLineTechnicalProblem)
        {
            productionLineTechnicalProblem.Creator = User.Identity.GetUserId();
            productionLineTechnicalProblem.AddDate = DateTime.Now;
            productionLineTechnicalProblem.LastModificationDate = DateTime.Now;
            productionLineTechnicalProblem.LastModifier = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.ProductionLineTechnicalProblem.Add(productionLineTechnicalProblem);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.PartID = new SelectList(db.Part, "ID", "Name", productionLineTechnicalProblem.PartID);
            ViewBag.ProductionLineID = new SelectList(db.ProductionLine, "ID", "ProductionLineName", productionLineTechnicalProblem.ProductionLineID);
            ViewBag.TechnicalProblemID = new SelectList(db.TechnicalProblem, "ID", "TechnicalProblemsName", productionLineTechnicalProblem.TechnicalProblemID);
            ViewBag.OperatorID = new SelectList(db.Operator, "OperatorID", "OperatorName", productionLineTechnicalProblem.OperatorID);
            return View(productionLineTechnicalProblem);
        }

        // GET: ProductionLineTechnicalProblems/Edit/5
        
        [Authorize(Roles = "ProductionLineTechnicalProblem_Edit , admin")]
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductionLineTechnicalProblem productionLineTechnicalProblem = await db.ProductionLineTechnicalProblem.FindAsync(id);
            if (productionLineTechnicalProblem == null)
            {
                return HttpNotFound();
            }

Towzin Source/Towzin/Views/ProductionLineTechnicalProblems/Create.cshtml
@model Towzin.Models.ProductionLineTechnicalProblem

@{
    ViewBag.Title = "مشکل فنی خط";
}

<h2>جدید</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>مشکلات فنی خط</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <span class="control-label col-md-2">خط تولید</span>
            <div class="col-md-2">
                @Html.DropDownList("ProductionLineID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductionLineID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">مشکل فنی</span>
            <div class="col-md-2">
                @Html.DropDownList("TechnicalProblemID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TechnicalProblemID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">کالا</span>
            <div class="col-md-2">
                @Html.DropDownList("PartID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PartID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">اپراتور</span>
            <div class="col-md-2">
                @Html.DropDownList("OperatorID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OperatorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">توضیحات مشکل فنی</span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescriptionTechnicalProblem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescriptionTechnicalProblem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">راه حل مشکل فنی</span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.SolutionTechnicalProblem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SolutionTechnicalProblem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">توضیحات</span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">فعال</span>
            <div class="col-md-2">
                <div class="checkbox">
                    @Html.EditorFor(model => model.State)
                    @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>



<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="ذخیره" class="btn btn-default" />   |
        @Html.ActionLink("بازگشت به لیست", "Index")
    </div>
</div>
</div>    
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Towzin Source/Towzin/Views/ProductionLineTechnicalProblems/Delete.cshtml
@model Towzin.Models.ProductionLineTechnicalProblem


@{
    ViewBag.Title = "حذف";
}

<h2>حذف</h2>

<h3>آیا از حذف این مورد مطمئن هستید؟</h3>
<div>
    <h4>مشکلات فنی خط</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            <span>خط تولید</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductionLine.ProductionLineName)
        </dd>
        <dt>
            <span>مشکل فنی</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TechnicalProblem.TechnicalProblemsName)
        </dd>
        <dt>
            <span> کالا</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Part.Name)
        </dd>


        <dt>
            <span>اپراتور</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Operator.OperatorName)
        </dd>

        <dt>
            <span> توضیحات مشکل فنی</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescriptionTechnicalProblem)
        </dd>

        <dt>
            <span> راه حل مشکل فنی</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SolutionTechnicalProblem)
        </dd>

        <dt>
            <span> توضیحات</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            <span> فعال</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="حذف" class="btn btn-default" /> |
            @Html.ActionLink("بازگشت به لیست", "Index")
        </div>
    }
</div>

Towzin Source/Towzin/Views/ProductionLineTechnicalProblems/Details.cshtml
@model Towzin.Models.ProductionLineTechnicalProblem

@{
    ViewBag.Title = "جزئیات";
}

<h2>جزئیات</h2>

<div>
    <h4>مشکلات فنی خط</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            <span>خط تولید</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductionLine.ProductionLineName)
        </dd>
        <dt>
            <span>مشکل فنی</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TechnicalProblem.TechnicalProblemsName)
        </dd>
        <dt>
            <span> کالا</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Part.Name)
        </dd>


        <dt>
            <span>اپراتور</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Operator.OperatorName)
        </dd>

        <dt>
            <span> توضیحات مشکل فنی</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescriptionTechnicalProblem)
        </dd>

        <dt>
            <span> راه حل مشکل فنی</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SolutionTechnicalProblem)
        </dd>

        <dt>
            <span> توضیحات</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            <span> فعال</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("ویرایش", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("بازگشت به لیست", "Index")
</p>

Towzin Source/Towzin/Views/ProductionLineTechnicalProblems/Edit.cshtml
@model Towzin.Models.ProductionLineTechnicalProblem

@{
    ViewBag.Title = "ویرایش مشکلات فنی خط";
}

<h2>ویرایش</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>مشکل فنی خط</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            <span class="control-label col-md-2">خط تولید</span>
            <div class="col-md-2">
                @Html.DropDownList("ProductionLineID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductionLineID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">مشکل فنی</span>
            <div class="col-md-2">
                @Html.DropDownList("TechnicalProblemID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TechnicalProblemID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">کالا</span>
            <div class="col-md-2">
                @Html.DropDownList("PartID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PartID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">اپراتور</span>
            <div class="col-md-2">
                @Html.DropDownList("OperatorID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OperatorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">توضیحات مشکل فنی</span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescriptionTechnicalProblem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescriptionTechnicalProblem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">راه حل مشکل فنی</span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.SolutionTechnicalProblem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SolutionTechnicalProblem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">توضیحات</span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">فعال</span>
            <div class="col-md-2">
                <div class="checkbox">
                    @Html.EditorFor(model => model.State)
                    @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group" hidden>
            @Html.LabelFor(model => model.Creator, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Creator, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Creator, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.AddDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.LastModifier, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastModifier, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastModifier, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.LastModificationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastModificationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastModificationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.Version, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Version, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Version, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ذخیره" class="btn btn-default" />  |
                @Html.ActionLink("بازگشت به لیست", "Index")
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Towzin Source/Towzin/Views/ProductionLineTechnicalProblems/Index.cshtml
@model PagedList.IPagedList<Towzin.Models.VW_ProductionLineTechnicalProblem_Index>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}

<h2>مشکلات خط تولید</h2>
@using (Html.BeginForm("Index", "ProductionLineTechnicalProblems", FormMethod.Get))
{
    <p>
        @Html.TextBox("SearchString")
        <input type="submit" value="جستجو" style="font-size:large" class="glyphicon-search" />

    </p>
}
<h3>
    <i style="font-family:W_nazanin" class="glyphicon glyphicon-plus gi-5x">
        @Html.ActionLink("جدید", "Create")

    </i>
</h3>

<div class="container">


    <table class="table table-bordered">

        <tr class="alert-success" style="font-size:large">
            <th>
                <b>ردیف</b>
            </th>
            <th>
                @Html.ActionLink("خط تولید", "Index", new { sortOrder = ViewBag.T1SortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("مشکل فنی", "Index", new { sortOrder = ViewBag.T2SortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("کالا", "Index", new { sortOrder = ViewBag.T3SortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("کد کالا", "Index", new { sortOrder = ViewBag.T4SortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("اپراتور", "Index", new { sortOrder = ViewBag.T5SortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("توضیحات مشکل", "Index", new { sortOrder = ViewBag.T6SortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("راه حل مشکل", "Index", new { sortOrder = ViewBag.T7SortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("توضیحات", "Index", new { sortOrder = ViewBag.T8SortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("وضعیت", "Index", new { sortOrder = ViewBag.T9SortParm, currentFilter = ViewBag.CurrentFilter })
            </th>

            <th></th>
        </tr>

        @{int rownumber = 0;}
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @{ rownumber++;}
                    @rownumber

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductionLineName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TechnicalProblemsName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PartCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OperatorName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DescriptionTechnicalProblem)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SolutionTechnicalProblem)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>
                <td>
                    @Html.ActionLink("ویرایش", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("جزئیات", "Details", new { id = item.ID }) |
                    @Html.ActionLink("حذف", "Delete", new { id = item.ID })
                </td>
            </tr>
                        }

    </table>
</div>
<br />
صفحه @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) از @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))