Towzin Source/Towzin/Models/ProductionLine.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Towzin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionLine()
        {
            this.ProductionLineTechnicalProblem = new HashSet<ProductionLineTechnicalProblem>();
            this.Order = new HashSet<Order>();
        }
    
        public long ID { get; set; }
        public string ProductionLineName { get; set; }
        public string ProductionLineLatinName { get; set; }
        public string Description { get; set; }
        public bool State { get; set; }
        public string Creator { get; set; }
        public System.DateTime AddDate { get; set; }
        public string LastModifier { get; set; }
        public System.DateTime LastModificationDate { get; set; }
        public byte[] Version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionLineTechnicalProblem> ProductionLineTechnicalProblem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}

Towzin Source/Towzin/Controllers/ProductionLinesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Towzin.Models;
using Microsoft.AspNet.Identity;
using PagedList;

namespace Towzin.Controllers
{
    public class ProductionLinesController : Controller
    {
        private TowzinEntities1 db = new TowzinEntities1();

        // GET: ProductionLines

        [Authorize(Roles = "ProductionLine_Index , admin")]
        public async Task<ActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.T1SortParm = String.IsNullOrEmpty(sortOrder) ? "T1" : "";
            ViewBag.T2SortParm = sortOrder == "T2" ? "T2_desc" : "T2";
            ViewBag.T3SortParm = sortOrder == "T3" ? "T3_desc" : "T3";
            ViewBag.T4SortParm = sortOrder == "T4" ? "T4_desc" : "T4";
 


            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var ProductionLine = from s in db.ProductionLine
                                select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                ProductionLine = ProductionLine.Where(s => s.ProductionLineName.Contains(searchString) || s.ProductionLineLatinName.Contains(searchString) || s.Description .ToString().Contains(searchString) );
            }
            switch (sortOrder)
            {
                case "T1_desc":
                    ProductionLine = ProductionLine.OrderByDescending(s => s.ProductionLineName);
                    break;
                case "T2_desc":
                    ProductionLine = ProductionLine.OrderByDescending(s => s.ProductionLineLatinName);
                    break;
                case "T2":
                    ProductionLine = ProductionLine.OrderBy(s => s.ProductionLineLatinName);
                    break;
                case "T3_desc":
                    ProductionLine = ProductionLine.OrderByDescending(s => s.Description);
                    break;
                case "T3":
                    ProductionLine = ProductionLine.OrderBy(s => s.Description);
                    break;
                case "T4_desc":
                    ProductionLine = ProductionLine.OrderByDescending(s => s.State);
                    break;
                case "T4":
                    ProductionLine = ProductionLine.OrderBy(s => s.State);
                    break;
                
                default:
                    ProductionLine = ProductionLine.OrderBy(s => s.ProductionLineName);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(ProductionLine.ToPagedList(pageNumber, pageSize));
        }

        // GET: ProductionLines/Details/5
        
        [Authorize(Roles = "ProductionLine_Detail , admin")]
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductionLine productionLine = await db.ProductionLine.FindAsync(id);
            if (productionLine == null)
            {
                return HttpNotFound();
            }
            return View(productionLine);
        }

        // GET: ProductionLines/Create
        
        [Authorize(Roles = "ProductionLine_Create , admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductionLines/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        [Authorize(Roles = "ProductionLine_Create , admin")]
        public async Task<ActionResult> Create([Bind(Include = "ID,ProductionLineName,ProductionLineLatinName,Description,State,Creator,AddDate,LastModifier,LastModificationDate,Version")] ProductionLine productionLine)
        {
            productionLine.Creator = User.Identity.GetUserId();
            productionLine.AddDate = DateTime.Now;
            productionLine.LastModificationDate = DateTime.Now;
            productionLine.LastModifier = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.ProductionLine.Add(productionLine);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(productionLine);
        }

        // GET: ProductionLines/Edit/5
        
        [Authorize(Roles = "ProductionLine_Edit , admin")]
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductionLine productionLine = await db.ProductionLine.FindAsync(id);
            if (productionLine == null)
            {
                return HttpNotFound();
            }
            return View(productionLine);
        }

        // POST: ProductionLines/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        [Authorize(Roles = "ProductionLine_Edit , admin")]
        public async Task<ActionResult> Edit([Bind(Include = "ID,ProductionLineName,ProductionLineLatinName,Description,State,Creator,AddDate,LastModifier,LastModificationDate,Version")] ProductionLine productionLine)
        {
            productionLine.LastModificationDate = DateTime.Now;
            productionLine.LastModifier = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.Entry(productionLine).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(productionLine);
        }

        // GET: ProductionLines/Delete/5
         
        [Authorize(Roles = "ProductionLine_Delete , admin")]
        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductionLine productionLine = await db.ProductionLine.FindAsync(id);
            if (productionLine == null)
            {
                return HttpNotFound();
            }
            return View(productionLine);
        }

        // POST: ProductionLines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        
        [Authorize(Roles = "ProductionLine_Delete , admin")]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            ProductionLine productionLine = await db.ProductionLine.FindAsync(id);
            db.ProductionLine.Remove(productionLine);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Towzin Source/Towzin/Views/ProductionLines/Create.cshtml
@model Towzin.Models.ProductionLine

@{
    ViewBag.Title = "جدید";
}

<h2>جدید</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>خط تولید</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <span class="control-label col-md-2">عنوان خط تولید</span>
            <div class="col-md-4">
                @Html.EditorFor(model => model.ProductionLineName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductionLineName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">عنوان لاتین خط تولید</span>
            <div class="col-md-4">
                @Html.EditorFor(model => model.ProductionLineLatinName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductionLineLatinName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">توضیحات</span>
            <div class="col-md-4">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">وضعیت</span>
            <div class="col-md-4">
                <div class="checkbox">
                    @Html.EditorFor(model => model.State)
                    @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ذخیره" class="btn btn-default" />   |
                @Html.ActionLink("بازگشت به لیست", "Index")
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Towzin Source/Towzin/Views/ProductionLines/Delete.cshtml
@model Towzin.Models.ProductionLine

@{
    ViewBag.Title = "حذف";
}

<h2>حذف</h2>

<h3>آیا از حذف این مورد مطمئن هستید؟</h3>
<div>
    <h4>خط تولید</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <span> عنوان خط تولید</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductionLineName)
        </dd>

        <dt>
            <span> عنوان لاتین خط تولید</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductionLineLatinName)
        </dd>

        <dt>
            <span> توضیحات</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            <span> وضعیت</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="حذف" class="btn btn-default" /> |
            @Html.ActionLink("بازگشت به لیست", "Index")
        </div>
    }
</div>

Towzin Source/Towzin/Views/ProductionLines/Details.cshtml
.@model Towzin.Models.ProductionLine

@{
    ViewBag.Title = "جزئیات";
}

<h2>جزئیات</h2>

<div>
    <h4>خط تولید</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <span> عنوان خط تولید</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductionLineName)
        </dd>

        <dt>
            <span> عنوان لاتین خط تولید</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductionLineLatinName)
        </dd>

        <dt>
            <span> توضیحات</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            <span>وضعیت </span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("ویرایش", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("بازگشت به لیست", "Index")
</p>

Towzin Source/Towzin/Views/ProductionLines/Edit.cshtml
@model Towzin.Models.ProductionLine

@{
    ViewBag.Title = "ویرایش";
}

<h2>ویرایش</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>خط تولید</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            <span class="control-label col-md-2">عنوان خط تولید</span>
            <div class="col-md-4">
                @Html.EditorFor(model => model.ProductionLineName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductionLineName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">عنوان لاتین خط تولید</span>
            <div class="col-md-4">
                @Html.EditorFor(model => model.ProductionLineLatinName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductionLineLatinName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">توضیحات</span>
            <div class="col-md-6">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">وضعیت</span>
            <div class="col-md-4">
                <div class="checkbox">
                    @Html.EditorFor(model => model.State)
                    @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group" hidden>
            @Html.LabelFor(model => model.Creator, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Creator, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Creator, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.AddDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.LastModifier, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastModifier, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastModifier, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.LastModificationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastModificationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastModificationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.Version, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Version, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Version, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ذخیره" class="btn btn-default" />
                @Html.ActionLink("بازگشت ب لیست", "Index")
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Towzin Source/Towzin/Views/ProductionLines/Index.cshtml
@model PagedList.IPagedList<Towzin.Models.ProductionLine>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}
<h2>خط تولید</h2>
@using (Html.BeginForm("Index", "ProductionLines", FormMethod.Get))
{
    <p>
        @Html.TextBox("SearchString")
        <input type="submit" value="جستجو" style="font-size:large" class="glyphicon-search" />

    </p>
}
<h3>
    <i style="font-family:W_nazanin" class="glyphicon glyphicon-plus gi-5x">
        @Html.ActionLink("جدید", "Create")

    </i>
</h3>

<div class="container">


    <table class="table table-bordered">

        <tr class="alert-success" style="font-size:large">
            <th>
                <b>ردیف</b>
            </th>
            <th>
                @Html.ActionLink("عنوان", "Index", new { sortOrder = ViewBag.T1SortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("عنوان لاتین", "Index", new { sortOrder = ViewBag.T2SortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("توضیحات", "Index", new { sortOrder = ViewBag.T3SortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("فعال", "Index", new { sortOrder = ViewBag.T4SortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th></th>
        </tr>

@{int rownumber = 0;}
@foreach (var item in Model)
{
    <tr>
        <td>
            @{ rownumber++;}
            @rownumber

        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductionLineName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductionLineLatinName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.ActionLink("ویرایش", "Edit", new { id = item.ID }) |
            @Html.ActionLink("جزئیات", "Details", new { id = item.ID }) |
            @Html.ActionLink("حذف", "Delete", new { id = item.ID })
        </td>
    </tr>
                }

    </table>
</div>
<br />
صفحه @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) از @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))