Towzin Source/Towzin/Models/PartSpecification.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Towzin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartSpecification
    {
        public long ID { get; set; }
        public long PartID { get; set; }
        public long SpecificationID { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public bool State { get; set; }
        public string Creator { get; set; }
        public System.DateTime AddDate { get; set; }
        public string LastModifier { get; set; }
        public System.DateTime LastModificationDate { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual Specification Specification { get; set; }
    }
}

Towzin Source/Towzin/Controllers/PartSpecificationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Towzin.Models;
using Microsoft.AspNet.Identity;
using PagedList;

namespace Towzin.Controllers
{
    public class PartSpecificationsController : Controller
    {
        private TowzinEntities1 db = new TowzinEntities1();

        // GET: PartSpecifications
     
        [Authorize(Roles = "PartSpecification_Index , admin")]
        public async Task<ActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.T1SortParm = String.IsNullOrEmpty(sortOrder) ? "T1" : "";
            ViewBag.T2SortParm = sortOrder == "T2" ? "T2_desc" : "T2";
            ViewBag.T3SortParm = sortOrder == "T3" ? "T3_desc" : "T3";
            ViewBag.T4SortParm = sortOrder == "T4" ? "T4_desc" : "T4";
            ViewBag.T5SortParm = sortOrder == "T5" ? "T5_desc" : "T5";
            ViewBag.T6SortParm = sortOrder == "T6" ? "T6_desc" : "T6";



            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var VW_PartSpecification_Index = from s in db.VW_PartSpecification_Index
                                select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                VW_PartSpecification_Index = VW_PartSpecification_Index.Where(s => s.Name.Contains(searchString) || s.PartCode.Contains(searchString) || s.SpecificationName.ToString().Contains(searchString) || s.Value.ToString().Contains(searchString) || s.Description.ToString().Contains(searchString));
            }
            switch (sortOrder)
            {
                case "T1_desc":
                    VW_PartSpecification_Index = VW_PartSpecification_Index.OrderByDescending(s => s.Name);
                    break;
                case "T2_desc":
                    VW_PartSpecification_Index = VW_PartSpecification_Index.OrderByDescending(s => s.PartCode);
                    break;
                case "T2":
                    VW_PartSpecification_Index = VW_PartSpecification_Index.OrderBy(s => s.PartCode);
                    break;
                case "T3_desc":
                    VW_PartSpecification_Index = VW_PartSpecification_Index.OrderByDescending(s => s.SpecificationName);
                    break;
                case "T3":
                    VW_PartSpecification_Index = VW_PartSpecification_Index.OrderBy(s => s.SpecificationName);
                    break;
                case "T4_desc":
                    VW_PartSpecification_Index = VW_PartSpecification_Index.OrderByDescending(s => s.Value);
                    break;
                case "T4":
                    VW_PartSpecification_Index = VW_PartSpecification_Index.OrderBy(s => s.Value);
                    break;
                case "T5_desc":
                    VW_PartSpecification_Index = VW_PartSpecification_Index.OrderByDescending(s => s.Description);
                    break;
                case "T5":
                    VW_PartSpecification_Index = VW_PartSpecification_Index.OrderBy(s => s.Description);
                    break;
                case "T6_desc":
                    VW_PartSpecification_Index = VW_PartSpecification_Index.OrderByDescending(s => s.State);
                    break;
                case "T6":
                    VW_PartSpecification_Index = VW_PartSpecification_Index.OrderBy(s => s.State);
                    break;
               
                default:
                    VW_PartSpecification_Index = VW_PartSpecification_Index.OrderBy(s => s.Name);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(VW_PartSpecification_Index.ToPagedList(pageNumber, pageSize));
        }

        // GET: PartSpecifications/Details/5
        
        [Authorize(Roles = "PartSpecification_Detail , admin")]
        public async Task<ActionResult> Details(long? PartID,long? SpecificationID)
        {
            if (PartID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (SpecificationID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PartSpecification partSpecification = await db.PartSpecification.FindAsync(PartID,SpecificationID);
            if (partSpecification == null)
            {
                return HttpNotFound();
            }
            return View(partSpecification);
        }

        // GET: PartSpecifications/Create
        
        [Authorize(Roles = "PartSpecification_Create , admin")]
        public ActionResult Create()
        {
            ViewBag.PartID = new SelectList(db.Part, "ID", "Name");
            ViewBag.SpecificationID = new SelectList(db.Specification, "ID", "SpecificationName");
            return View();
        }

        // POST: PartSpecifications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        [Authorize(Roles = "PartSpecification_Create , admin")]
        public async Task<ActionResult> Create([Bind(Include = "ID,PartID,SpecificationID,Value,Description,State,Creator,AddDate,LastModifier,LastModificationDate,Version")] PartSpecification partSpecification)
        {
            partSpecification.Creator = User.Identity.GetUserId();
            partSpecification.AddDate = DateTime.Now;
            partSpecification.LastModificationDate = DateTime.Now;
            partSpecification.LastModifier = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.PartSpecification.Add(partSpecification);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.PartID = new SelectList(db.Part, "ID", "Name", partSpecification.PartID);
            ViewBag.SpecificationID = new SelectList(db.Specification, "ID", "SpecificationName", partSpecification.SpecificationID);
            return View(partSpecification);
        }

        // GET: PartSpecifications/Edit/5
        
        [Authorize(Roles = "PartSpecification_Edit , admin")]
        public async Task<ActionResult> Edit(long? PartID, long? SpecificationID)
        {
            if (PartID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (SpecificationID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PartSpecification partSpecification = await db.PartSpecification.FindAsync(PartID, SpecificationID);
            if (partSpecification == null)
            {
                return HttpNotFound();
            }
            ViewBag.PartID = new SelectList(db.Part, "ID", "Name", partSpecification.PartID);
            ViewBag.SpecificationID = new SelectList(db.Specification, "ID", "SpecificationName", partSpecification.SpecificationID);
            return View(partSpecification);
        }

        // POST: PartSpecifications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        [Authorize(Roles = "PartSpecification_Edit , admin")]
        public async Task<ActionResult> Edit([Bind(Include = "ID,PartID,SpecificationID,Value,Description,State,Creator,AddDate,LastModifier,LastModificationDate,Version")] PartSpecification partSpecification)
        {
            partSpecification.LastModificationDate = DateTime.Now;
            partSpecification.LastModifier = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.Entry(partSpecification).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.PartID = new SelectList(db.Part, "ID", "Name", partSpecification.PartID);
            ViewBag.SpecificationID = new SelectList(db.Specification, "ID", "SpecificationName", partSpecification.SpecificationID);
            return View(partSpecification);
        }

        // GET: PartSpecifications/Delete/5
        
        [Authorize(Roles = "PartSpecification_Delete , admin")]
        public async Task<ActionResult> Delete(long? PartID, long? SpecificationID)
        {
            if (PartID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (SpecificationID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PartSpecification partSpecification = await db.PartSpecification.FindAsync(PartID, SpecificationID);
            if (partSpecification == null)
            {
                return HttpNotFound();
            }
            return View(partSpecification);
        }

        // POST: PartSpecifications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        
        [Authorize(Roles = "PartSpecification_Delete , admin")]
        public async Task<ActionResult> DeleteConfirmed(long? PartID, long? SpecificationID)
        {
            PartSpecification partSpecification = await db.PartSpecification.FindAsync(PartID, SpecificationID);

Towzin Source/Towzin/Views/PartSpecifications/Create.cshtml
@model Towzin.Models.PartSpecification

@{
    ViewBag.Title = "جدید";
}

<h2>جدید</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>PartSpecification</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <span class="control-label col-md-2">کالا</span>
            <div class="col-md-10">
                @Html.DropDownList("PartID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PartID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">ویژگی</span>
            <div class="col-md-2">
                @Html.DropDownList("SpecificationID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SpecificationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">مقدار</span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">توضیحات</span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">وضعیت</span>
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.State)
                    @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>2

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ذخیره" class="btn btn-default" />  |
                @Html.ActionLink("بازگشت به لیست", "Index")
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Towzin Source/Towzin/Views/PartSpecifications/Delete.cshtml
@model Towzin.Models.PartSpecification

@{
    ViewBag.Title = "Delete";
}
@{
    ViewBag.Title = "Delete";
}

<h2>حذف</h2>

<h3>آیا از حذف این مورد مطمئن هستید؟</h3>
<div>
    <h4>ویژگی کالا</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <span>کالا</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Part.Name)
        </dd>

        <dt>
            <span>ویژگی</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Specification.SpecificationName)
        </dd>


        <dt>
            <span>مقدار</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        <dt>
            <span>توضیحات</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            <span>فعال</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>



    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="حذف" class="btn btn-default" /> |
            @Html.ActionLink("بازگشت به لیست", "Index")
        </div>
    }
</div>

Towzin Source/Towzin/Views/PartSpecifications/Details.cshtml
@model Towzin.Models.PartSpecification

@{
    ViewBag.Title = "Details";
}

<h2>جزییات</h2>

<div>
    <h4>ویژگی کالا</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <span>کالا</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Part.Name)
        </dd>

        <dt>
            <span>ویژگی</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Specification.SpecificationName)
        </dd>


        <dt>
            <span>مقدار</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        <dt>
            <span>توضیحات</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            <span>فعال</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>



    </dl>
</div>
<p>
    @Html.ActionLink("ویرایش", "Edit", new { PartID = Model.PartID, SpecificationID = Model.SpecificationID}) |
    @Html.ActionLink("بازگشت به لیست", "Index")
</p>

Towzin Source/Towzin/Views/PartSpecifications/Edit.cshtml
@model Towzin.Models.PartSpecification

@{
    ViewBag.Title = "ویرایش";
}

<h2>ویرایش</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="form-horizontal">
        <h4>ویژگی کالا</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <span class="control-label col-md-2">کالا</span>
            <div class="col-md-10">
                @Html.DropDownList("PartID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PartID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">ویژگی</span>
            <div class="col-md-2">
                @Html.DropDownList("SpecificationID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SpecificationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">مقدار</span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">توضیحات</span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">وضعیت</span>
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.State)
                    @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group" hidden>
            @Html.LabelFor(model => model.Creator, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Creator, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Creator, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.AddDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.LastModifier, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastModifier, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastModifier, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.LastModificationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastModificationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastModificationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.Version, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Version, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Version, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ذخیره" class="btn btn-default" />  |
                @Html.ActionLink("بازگشت به لیست", "Index")
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Towzin Source/Towzin/Views/PartSpecifications/Index.cshtml
@model PagedList.IPagedList<Towzin.Models.VW_PartSpecification_Index>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}

<h2>ویژگی های کالا</h2>
@using (Html.BeginForm("Index", "PartSpecifications", FormMethod.Get))
{
    <p>
        @Html.TextBox("SearchString")
        <input type="submit" value="جستجو" style="font-size:large" class="glyphicon-search" />

    </p>
}
<h3>
    <i style="font-family:W_nazanin" class="glyphicon glyphicon-plus gi-5x">
        @Html.ActionLink("جدید", "Create")

    </i>
</h3>

<div class="container">


    <table class="table table-bordered">

        <tr class="alert-success" style="font-size:large">
            <th>
                <b>ردیف</b>
            </th>

            <th>
                @Html.ActionLink("کالا", "Index", new { sortOrder = ViewBag.T1SortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("کد کالا", "Index", new { sortOrder = ViewBag.T2SortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("ویژگی", "Index", new { sortOrder = ViewBag.T3SortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("مقدار", "Index", new { sortOrder = ViewBag.T4SortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("توضیحات", "Index", new { sortOrder = ViewBag.T5SortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("فعال", "Index", new { sortOrder = ViewBag.T6SortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th></th>
        </tr>

        @{int rownumber = 0;}
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @{ rownumber++;}
                    @rownumber

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PartCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SpecificationName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Value)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>
                <td>
                    @Html.ActionLink("ویرایش", "Edit", new { PartID = item.PartID, SpecificationID = item.SpecificationID }) |
                    @Html.ActionLink("جزئیات", "Details", new { PartID = item.PartID, SpecificationID = item.SpecificationID }) |
                    @Html.ActionLink("حذف", "Delete", new { PartID = item.PartID, SpecificationID = item.SpecificationID })
                </td>
            </tr>
                        }

    </table>
</div>
<br />
صفحه @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) از @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))